### ISSUE TITLE
Building Network keeps failing

### ISSUE THREAD

**Issue by kvdmdi2** [Esri/street-data-processing-tools#58]
Hi,

I'm able to run the tool with TomTom data for Belgium and the border regions of Netherlands, France, Luxemburg an Germany.
This networks Builds and dissolves without problem.

When I try to create the same but the whole of France also.  The tool runs OK, but the build fails (see screenshot)

![Schermafbeelding 2024-03-26 145030](https://github.com/Esri/street-data-processing-tools/assets/98943821/37925c6d-63a5-4ed9-8929-ce551baf4ed5)

Any ideas on this ?

thx 

Koen

**Comment by mmorang** [comment]
Hmm, not off the top of my head.  A couple of questions:
1. What version of ArcGIS Pro are you using?
2. Did you make any changes to the network after creating it with the Street Data Processing Tools?
3. Have you checked to see if you're out of disk space or if your machine ran out of memory or something like that?  The message kind of seems like a resource issue.
4. Can share the network dataset with me so we can debug it?  I can provide a secure file transfer option if needed.

**Comment by kvdmdi2** [comment]
1. ArcGIS Pro 3.2.1
2. No Changes
3. 36,6 GB free
4. Can provide the network data file an de source file if you want.  Do You have a mail address (I have them on onedrive) or a place where I can put them

**Comment by mmorang** [comment]
Okay, I can send you a secure file transfer link, but it has to come by e-mail, so I need your e-mail address.  If you don't want to post it here, you can send me an e-mail at mmorang@esri.com.

**Comment by chritomix** [comment]
Hi, from my experience, i would also say it is your disk space. 36Go believe, me it is not enough for whole France.

**Comment by kvdmdi2** [comment]
I freed some disk space and I managed to build the network.  Thx for the advice.

**Comment by mmorang** [comment]
Great, glad that fixed it.

I was able to reproduce the problem you experienced on a machine with < 30Gb free disk space,  and when I cleaned up some space on that machine, it went away.  I was able to successfully build the network on a machine running Pro 3.2.2 and Pro 3.3 (forthcoming release).

**Comment by JamieEames** [comment]
For NAVSTREETS In the UK the BR_RTEDIR appears to not be populated, which raises this error when you run the toolbox:

line 1780, in _populate_signposts_and_signposts_streets
    branch_text = record["BR_RTEID"].strip()
                  ^^^^^^^^^^^^^^^^^^^^^^^^
﻿AttributeError: 'NoneType' object has no attribute 'strip'

**Comment by mmorang** [comment]
@JamieEames Thanks for reporting this problem, and sorry for the trouble!  I fixed the bug in the latest release, available here: https://github.com/Esri/street-data-processing-tools/releases/tag/v2.1.1

If you encounter further issues, please open a new issue instead of commenting on an old, closed one.  It will make it much easier for me to track.
